
GET http://localhost:3001/clientes HTTP/1.1
content-type: application/json

###

POST http://localhost:3001/cliente HTTP/1.1
content-type: application/json

{
    "nome": "Mario das Neves",
    "login": "mario",
    "senha": "123",
    "email": "mario@outlook.com"
}

###

GET http://localhost:3001/cliente/2 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3001/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome": "Rodrigo Tognin",
    "email": "wmetalboy@gmail.com"
}